### ISSUE TITLE
Make other map projection available

### ISSUE THREAD

**Issue by natrius** [ad3m3r5/scratch-map#2]
It seems you are using the mercator projection. Fun-fact, it was never intended for this kind of use - it was solely made for nautical purposes. Cartographers nearly made everyone aware of that but then google destroyed everything as it does everytimes and made Mercator the 'standard' again :D This just a funfact. See https://en.wikipedia.org/wiki/Mercator_projection for more information. 

Anyway, it would be fun to support some different projection-variants. I don't know how hard this would be, but there are some references at https://en.wikipedia.org/wiki/Map_projection 
I think that would be awesome :) (As a fun-gimmic a randomizer for everyday a new projection :D)

**Comment by Lockszmith-GH** [comment]
+1, self hosting = individualism. This chimes to the philosophy so well.

**Comment by ad3m3r5** [comment]
The world map actually uses a Robinson projection, rather than Mercator, although they do appear to be similar. I don't currently have any plans to add any other projections, but it does seem like a fun idea!

To comply with the current application setup, if you wanted to add a new world map projection, the SVG layout would have to be:
```
<svg id="svg-map">
  <g class="countries">
    <g id="US">
        US specific paths
    </g>
    ...
  </g>
</svg>

```

**Comment by ad3m3r5** [comment]
For the simplicity aspect of the project, I'm going to go ahead and close this. However, if someone did implement a way to dynamically set the map projection, I would gladly consider merging it in.
Thanks again for the idea!
